version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 435627631709.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t kong-gateway:3.9 .
      - docker tag kong-gateway:3.9 435627631709.dkr.ecr.us-east-1.amazonaws.com/kong-gateway:3.9
      - docker tag kong-gateway:3.9 435627631709.dkr.ecr.us-east-1.amazonaws.com/kong-gateway:latest
  post_build:
    commands:
      - docker push 435627631709.dkr.ecr.us-east-1.amazonaws.com/kong-gateway:3.9
      - docker push 435627631709.dkr.ecr.us-east-1.amazonaws.com/kong-gateway:latest
      - echo Kong image build and push completed
